apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
type: Opaque
data:
  dc-connection-string-secret: U2VydmVyPW1zc3FsLXNlcnZpY2U7RGF0YWJhc2U9UHJvZHVjdHNEQjtVc2VyPVNBO1Bhc3N3b3JkPUdhZGdldF8wMjs=
