apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mvc-deployment
  name: mvc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvc-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mvc-deployment
    spec:
      containers:
      - image: suiteresearchlab/mvc-app:v2.#{$(Build:Buildid)}#
        name: mvc-app
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__ProductsContext
          value: Server=mssql-service;Database=ProductsDB;User=SA;Password=Gadget_02;
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-service
spec:
  type: LoadBalancer
  selector:
    app: mvc-deployment
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30100
      # ##[error]invalid argument "***/mvc-app:v2.$(build:buildid)" for "-t, --tag" flag: invalid reference format